---

- name: detect installed vaultwarden
  when:
    - not running_in_check_mode
  block:
    - name: detect if vaultwarden exists
      ansible.builtin.stat:
        path: /usr/bin/vaultwarden
      register: vaultwarden_binary_file

    - name: define vaultwarden_installed
      ansible.builtin.set_fact:
        vaultwarden_installed: "{{ vaultwarden_binary_file.stat.exists }}"

- name: merge vaultwarden configuration between defaults and custom
  when:
    - not running_in_check_mode
  ansible.builtin.set_fact:
    vaultwarden_config: "{{ vaultwarden_defaults_config | combine(vaultwarden_config, recursive=True) }}"

- name: debian based
  become: true
  when:
    - not running_in_check_mode
    - ansible_facts.os_family | lower == 'debian'
    # - php_version | int == 8
  block:
    - name: define keyring name
      ansible.builtin.set_fact:
        _vaultwarden_keyring: "{{ 'vaultwarden-keyring.gpg' if ansible_facts.distribution_major_version | int == 13 else 'bananian-keyring.gpg' }}"


    - name: debian
      when:
        ansible_facts.distribution | lower == "debian"
      bodsch.core.apt_sources:
        name: vaultwarden
        filename: vaultwarden.sources
        uris:
          - http://bitwarden-deb.tech-network.de
        suites: "{{ ansible_facts.distribution_release | lower }}"
        components:
          - main
        signed_by: "/usr/share/keyrings/{{ _vaultwarden_keyring }}"
        key:
          method: download
          url: "https://bitwarden-deb.tech-network.de/{{ _vaultwarden_keyring }}"
          dest: "/usr/share/keyrings/{{ _vaultwarden_keyring }}"
          # validate: false
        update_cache: true

- name: create policy-rc.d
  when:
    - not running_in_check_mode
    - not vaultwarden_installed
    - ansible_facts.os_family | lower == 'debian'
  ansible.builtin.copy:
    dest: /usr/sbin/policy-rc.d
    content: |
      #!/bin/sh
      exit 101
    mode: "0755"
  tags:
    - vaultwarden
    - vaultwarden_install

- name: install package
  when:
    - not running_in_check_mode
    - not vaultwarden_installed
  ansible.builtin.package:
    name: "{{ vaultwarden_packages }}"
    state: present
  tags:
    - vaultwarden
    - vaultwarden_install

- name: create vaultwarden custom directory tree
  when:
    - not running_in_check_mode
  bodsch.core.directories:
    owner: vaultwarden
    group: vaultwarden
    mode: "0775"
    base_path: "{{ vaultwarden_config.directories.data }}"
    paths:
      - path: icon_cache
      - path: attachments
      - path: sends
      - path: tmp
      - path: templates

- name: systemd
  when:
    - not running_in_check_mode
    - ansible_facts.service_mgr | lower == "systemd"
  block:
    - name: create systemd overwrite directory
      ansible.builtin.file:
        state: directory
        path: /etc/systemd/system/vaultwarden.service.d
        mode: "0750"

    - name: create the systemd service file
      ansible.builtin.template:
        src: init/systemd/vaultwarden.service.j2
        dest: /etc/systemd/system/vaultwarden.service.d/override.conf
        owner: root
        group: root
        mode: "0644"
      notify:
        - daemon-reload
        - restart service

- name: remove policy-rc.d
  when:
    - not running_in_check_mode
    - not vaultwarden_installed
    - ansible_facts.os_family | lower == 'debian'
  ansible.builtin.file:
    path: /usr/sbin/policy-rc.d
    state: absent
  tags:
    - vaultwarden
    - vaultwarden_install

- name: install vaultwarden web
  when:
    - not running_in_check_mode
    - vaultwarden_config.web_vault.enabled | default('false') | bool
  ansible.builtin.include_tasks: install/vaultwarden_web.yml

...
